Submission script supports LXBATCH.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -11,12 +11,20 @@ function PrintUsage()
 	echo -e "	-no-run, -dno		do not run the program for any diagonal, just compile"
 	echo -e "	-O <option>		pass the option to the program"
 	echo -e "	-no-bckg		do no run compilation and programs in background"
+	echo -e "	-lxbatch		prepare job for LXBATCH instead of executing locally"
+	echo -e "	-submit			submit job to LXBATCH, implies -lxbatch option"
 }
 
 #----------------------------------------------------------------------------------------------------
 
 doNotRun="f"
 runInBackground="y"
+
+lxbatch="n"
+submit="n"
+
+bsub_options="pool>5000"
+bsub_queue="8nh"
 
 #----------------------------------------------------------------------------------------------------
 
@@ -76,19 +84,42 @@ function RunOneDir()
 	label="$tag @ $dir"
 	log="${tag}.log_run"
 
-	echo "$label > running$optionsStr"
-	"./$exe_file" $options &> "$log"
-	errCode="$?"
-	case "$errCode" in
-		0)
-			echo "$label > done"
-			;;
+	if [ "$lxbatch" == "y" ]
+	then
+		local cwd=`pwd -P`
+		local job_dir="$cwd"
+		local job_file=".${tag}.job"
+		local job_log_file=".${tag}.log_job"
 
-		*)
-			echo "$label > run error ($errCode)"
-			if [ "$par_more" -eq 1 ]; then tail -n 5 "$log"; fi
-			;;
-	esac
+		cat "$top_dir/job_template" | sed "\
+				s|\$JOB_DIR|$job_dir|; \
+				s|\$JOB_LOG_FILE|$job_log_file|; \
+				s|\$COMMAND|{ time \"./$exe_file\" $options ; } \&> \"$log\"|; \
+			" > "$job_file"
+		chmod u+x "$job_file"
+
+		if [ "$submit" == "y" ]
+		then
+			result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
+			echo "$label > $result"
+		else
+			echo "$label > would be submitted (use -submit option)"
+		fi
+	else
+		echo "$label > running$optionsStr"
+		{ time "./$exe_file" $options ; } &> "$log"
+		errCode="$?"
+		case "$errCode" in
+			0)
+				echo "$label > done"
+				;;
+
+			*)
+				echo "$label > run error ($errCode)"
+				if [ "$par_more" -eq 1 ]; then tail -n 5 "$log"; fi
+				;;
+		esac
+	fi
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -118,6 +149,15 @@ do
 
 		"-no-bckg")
 			runInBackground="n"
+			;;
+
+		"-lxbatch")
+			lxbatch="y"
+			;;
+
+		"-submit")
+			lxbatch="y"
+			submit="y"
 			;;
 
 		*)
